[package]
name = "abacas"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "polynomial"
harness = false

[dependencies]
rug.workspace = true

[dev-dependencies]
rand.workspace = true
divan.workspace = true
rand_xoshiro.workspace = true
