name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Configure Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate Files
        run: cargo doc --lib --no-deps

      - name: Add Redirect
        run: echo '<meta http-equiv="refresh" content="0;url=abacas/index.html">' > target/doc/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: target/doc

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v5
