name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Configure Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Linter
        run: cargo clippy --verbose

      - name: Run Tests
        run: cargo test --verbose

      - name: Install Formatter
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run Formatter
        run: cargo +nightly fmt --check --verbose
