name: Tests

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run Linter
        run: cargo clippy --verbose

      - name: Run Tests
        run: cargo test --verbose
