name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - name: Run Linter
        run: cargo clippy --verbose

      - name: Run Tests
        run: cargo test --verbose

      - name: Install Formatter
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run Formatter
        run: cargo +nightly fmt --check --verbose
