name: Tests

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run Linter
        run: cargo clippy --verbose

      - name: Run Tests
        run: cargo test --verbose

      - name: Install Formatter
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run Formatter
        run: cargo +nightly fmt --check --verbose
